class ImageConstant {
  ImageConstant._();
  static const String baseAssets = "assets/images";
  static const String cropImage = "$baseAssets/crop.png";
  static const String linkDin = "$baseAssets/linkdin.png";
  static const String faceBook = "$baseAssets/facebook.png";
  static const String google = "$baseAssets/google.png";
  static const String home = "$baseAssets/home.png";
  static const String person = "$baseAssets/person.png";
  static const String notification = "$baseAssets/notification.png";
  static const String help = "$baseAssets/help.png";
  static const String frame = "$baseAssets/frame.png";
  static const String setting = "$baseAssets/setting.png";
  static const String logOut = "$baseAssets/logOut.png";
  static const String changePassword = "$baseAssets/changePassword.png";
  static const String cropFrame = "$baseAssets/cropFrame.png";
  static const String argiImage = "$baseAssets/agri.jpg";
  static const String sun = "$baseAssets/sun.png";
  static const String irrigation = "$baseAssets/irrigation.png";
  static const String chart = "$baseAssets/chart.png";
  static const String weather = "$baseAssets/weather.png";
  static const String paddy = "$baseAssets/paddy.png";
  static const String tomato = "$baseAssets/tomato.png";
  static const String potato = "$baseAssets/potato.png";
  static const String visibility = "$baseAssets/visibility.png";
  static const String wind = "$baseAssets/wind.png";
  static const String humidity = "$baseAssets/humidity.png";
  static const String cloudy = "$baseAssets/cloudy.png";
  static const String rainy = "$baseAssets/rainy.png";
}
